## Libs

In [96]:
import heapq as hq
import numpy as np
from tqdm import tqdm
import pandas as pd

In [3]:
df = pd.read_clipboard()
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2163 entries, 0 to 2162
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TIMESTAMP  2163 non-null   int64
 1   USER_ID    2163 non-null   int64
 2   ITEM_ID    2163 non-null   int64
dtypes: int64(3)
memory usage: 50.8 KB


TIMESTAMP  USER_ID  ITEM_ID
0     1595606386935036  3129206      588
1     1595606383603032  3129206      600
2     1595606354389024  3129206     2730
3     1595606305623231  1759488     2644
4     1595606278320013  3129206      298
...                ...      ...      ...
2158  1595520335157065  3982077     2739
2159  1595520232145049  3982077     2076
2160  1595520033463006  3529652      342
2161  1595520025218016   182834      506
2162  1595520013557009   182834      504

[2163 rows x 3 columns]

In [32]:
# x = df.USER_ID.value_counts()
# uid = x[x >= 3].index
# df.ITEM_ID.value_counts(), df[df.USER_ID.isin(uid)].ITEM_ID.value_counts()

df.groupby(["USER_ID", "ITEM_ID"]).size().to_frame("size").reset_index().sort_values("size", ascending=False)

USER_ID  ITEM_ID  size
0       85115      298     1
1437  3949605      612     1
1451  3949932      463     1
1450  3949605     2852     1
1449  3949605     2851     1
...       ...      ...   ...
715   2912641     2714     1
714   2912641      368     1
713   2899257     2645     1
712   2899257     2146     1
2162  4047933     2761     1

[2163 rows x 3 columns]

In [16]:
ary = np.array([[.9, -.2], [-1, -.8], [1, -1], [1, .9], [-.9, 1]])
ary @ ary.T

array([[ 0.85, -0.74,  1.1 ,  0.72, -1.01],
       [-0.74,  1.64, -0.2 , -1.72,  0.1 ],
       [ 1.1 , -0.2 ,  2.  ,  0.1 , -1.9 ],
       [ 0.72, -1.72,  0.1 ,  1.81,  0.  ],
       [-1.01,  0.1 , -1.9 ,  0.  ,  1.81]])

## Functions

In [ ]:
class ListNode(object):
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
        
    def __repr__(self):
        return f"{self.val} -> {self.next}"
    
    def __str__(self):
        return self.__repr__()

def compose_linkedlist(ary):
    if not len(ary):
        return None
    
    head = ptr = ListNode(ary[0])
    for i in range(1, len(ary)):
        ptr.next = ListNode(ary[i])
        ptr = ptr.next
    return head

def show_linkedlist(x):
    while x is not None:
        print(x)
        x = x.next


## Hash table implements

In [ ]:
class MyHashTable():
    def __init__(self, size):
        self.size = size
        self.table = [None] * self.size

    def my_hash(self, key):
        return int.from_bytes(bytes(key, "utf-8"), byteorder="big") % self.size

    def set(self, key, value):
        hash_value = self.my_hash(key)
        if self.table[hash_value] is None:
            self.table[hash_value] = [[key,value]]
        else:
            self.table[hash_value].append([key,value])

    def get(self, key):
        hash_value = self.my_hash(key)
        if self.table[hash_value] is not None:
            for bucket_key_value_pair in self.table[hash_value]:
                if bucket_key_value_pair[0] == key:
                    return bucket_key_value_pair[1]
        return None

In [97]:
from collections import defaultdict

class Solution(object):
    def __init__(self):
        self.done = set()
    
    def dist(self, nums, i, j):
        """"""
        return nums[j] - nums[i], (i, j)
    
    def maybe_push(self, nums, ary, i, j):
        if (i, j) not in self.done:
            val = self.dist(nums, i, j)
            self.done.add((i, j))
            hq.heappush(ary, val)
        return self
        
    def smallestDistancePair(self, nums, k):
        # dct = {}
        ret = []
        n = len(nums)
        nums.sort()
        ary = []
        for i in range(len(nums) - 1):
            self.maybe_push(nums, ary, i, i + 1)
            
        hq.heapify(ary)
        for i in range(k):
            d, coord = hq.heappop(ary)
            if coord[1] + 1 < n:
                self.maybe_push(nums, ary, coord[0], coord[1] + 1)
        return d
        
Solution().smallestDistancePair(inp, k=30)

40

## Smallest distance pair (Time exceeded)

In [ ]:
from heapq import heappop, heappush, heapify

class Solution:
    def smallestDistancePair(self, nums, k):
        n = len(nums)
        nums.sort()
        heap = [(nums[i + 1] - nums[i], i, i + 1) for i in range(n - 1)]
        heapify(heap)

        for _ in range(k):
            d, root, nei = heappop(heap)
            if nei + 1 < n:
                heappush(heap, (nums[nei + 1] - nums[root], root, nei + 1))

        return d
    
Solution().smallestDistancePair(inp, k=30)

## 2-sum

In [229]:
class Solution:
    def two_sum(self, ary, target):
        dct = {}
        for i, e in enumerate(ary):
            if target - e in dct:
                return [dct[target - e], i]
            else:
                dct[e] = i
                
        return None
    
Solution().two_sum([1, 2, 3, 3, 4, 5], 8)

[3, 5]

## Longest Substring Without Repeating Characters 

In [8]:
class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        from collections import Counter
        
        if not len(s):
            return 0
        
        l, dct, max_ = 0, {}, 0
        for i, w in enumerate(s):
            hit = w in dct
            if hit:
                max_ = max(max_, len(s[l:i]))
                l, dct = i, {}
                
            # Last round
            if i == len(s) - 1:
                r = i if hit else i + 1
                max_ = max(max_, len(s[l:r]))
                break
                
            dct[w] = i
                
        return max_
    
Solution().lengthOfLongestSubstring("aaaab") # aabaab!bb

2

## Container With Most Water

- 2 pointers approximation, better than brutal enumeration, check [Explanation of 2 pointer algo](https://leetcode.com/problems/container-with-most-water/discuss/6099/Yet-another-way-to-see-what-happens-in-the-O(n)-algorithm)

    ```
      1 2 3 4 5 6
    1 x ------- o
    2 x x       o
    3 x x x     |
    4 x x x x   |
    5 x x x x x |
    6 x x x x x x
    ```

In [265]:
class Solution:
    def maxArea(self, height: List[int]) -> int:
        _max = 0 
        
        l, r = 0, len(height)-1
        
        while l < r:
            
            _max = max(_max, min(height[l], height[r]) * (r-l))
            
            # for moving the left pointer
            if height[l] < height[r]: l += 1
              
            # moving the right pointer
            elif height[r] <= height[l]: r -= 1
               
        return _max

[(8, 6), (7, 8), (6, 2), (5, 4), (4, 5), (3, 7), (2, 3), (1, 0)]


## Sort

### Quick sort

In [226]:
# Quick sort in Python

# function to find the partition position
def partition(array, low, high):
  # choose the rightmost element as pivot
  pivot = array[high]

  # pointer for greater element
  i = low - 1

  # traverse through all elements
  # compare each element with pivot
  for j in range(low, high):
    if array[j] <= pivot:
      # if element smaller than pivot is found
      # swap it with the greater element pointed by i
      i = i + 1

      # swapping element at i with element at j
      (array[i], array[j]) = (array[j], array[i])
      # print(array, i, j)

  # swap the pivot element with the greater element specified by i
  (array[i + 1], array[high]) = (array[high], array[i + 1])
  # print(array, i + 1, high)
  # print("-" * 20)
  # return the position from where partition is done
  return i + 1

# function to perform quicksort
def quickSort(array=test, low=0, high=len(test) - 1):
  if low < high:

    # find pivot element such that
    # element smaller than pivot are on the left
    # element greater than pivot are on the right
    pi = partition(array, low, high)

    # recursive call on the left of pivot
    quickSort(array, low, pi - 1)
    # recursive call on the right of pivot
    quickSort(array, pi + 1, high)


# data = [8, 7, 2, 1, 0, 9, 6]
# print("Unsorted Array")
# print(data)

# size = len(data)

memory_usage(quickSort)


[99.9375, 99.9375, 99.9375, 99.9375, 99.9375, 99.9375]

### quick sort without considering memory usage

In [224]:
from memory_profiler import memory_usage

def quick_sort(ary=test):
    if len(ary) <= 1:
        return ary
    
    pivot, l_part, r_part = ary[-1], [], []
    for i in range(len(ary) - 1):
        if ary[i] <  pivot: 
            l_part.append(ary[i])
        else:
            r_part.append(ary[i])
            
    return quick_sort(l_part) + [pivot] + quick_sort(r_part)


# print(quick_sort(test) == sorted(test))
memory_usage(quick_sort)

[98.859375,
 98.859375,
 98.859375,
 98.859375,
 98.859375,
 98.859375,
 99.18359375,
 99.84375,
 99.9375]

### Bubble sort

- O(n**2) 一直把最大的往前推進, 像Bubble一樣浮出, 所以叫做Bubble sort

In [ ]:
ary = np.random.randint(20, size=10)
print(ary)

base = np.zeros([10, 10])
base[0] = ary
for i in range(len(ary) - 1):
    for j in range(len(ary) - 1 - i):
        if ary[j] > ary[j + 1]:
            ary[j], ary[j + 1] = ary[j + 1], ary[j]
    base[i + 1] = ary
base

## 3-Sum

In [38]:
class Solution:
    def threeSum(self, nums):
        """"""
        ary = []
        cache = set()
        nums.sort()
        for i in range(len(nums) - 2):
            t = nums[i]
            l, r = i + 1, len(nums) - 1
            while l < r:
                _sum = nums[l] + t + nums[r]
                if _sum == 0:
                    tp = tuple(sorted([nums[l], t, nums[r]]))
                    if tp not in cache:
                        cache.add(tp)
                        
                    l += 1
                    r -= 1
                    while l < r:
                        if nums[l] == nums[l + 1]:
                            l += 1
                        if nums[r] == nums[r - 1]:
                            r -= 1
                        
                elif _sum < 0:
                    l += 1
                else:
                    r -= 1
        return list(map(list, cache))

## Remove Nth Node From End of List

In [13]:
from collections import deque

class Solution(object):
    def removeNthFromEnd(self, head, n):
        dummy_head, cursor, idx = ListNode(), head, 0
        dummy_head.next = head
        
        q = deque([], n + 1)
        
        while cursor is not None:
            q.append(cursor)
            cursor = cursor.next
            
        q_len = len(q)
            
        # If length of dequeue == n
        if q_len == n + 1:
            q[0].next = q[2] if q_len >= 3 else None
            dummy_head = dummy_head.next
        elif q_len <= n :
            dummy_head = q[1] if q_len >= 2 else None
            
        return dummy_head

1
3


In [140]:
class Solution:
    def isValid(self, s: str) -> bool:
        left, right = "({[", ")}]"
        left, right = dict(zip(left, right)), dict(zip(right, left))
        queue = []
        for i, w in enumerate(s):
            if w in left:
                queue.append(w)
                
            if w in right:
                if not len(queue):
                    return False
                
                if right[w] != queue.pop():
                    return False
                
        if len(queue) > 0:
            return False
        
        return True

Solution().isValid("(())")

True

## Merge 2 Sorted Lists

In [274]:
class ListNode(object):
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
        
    def __repr__(self):
        return f"{self.val} -> {self.next}"
    
    def __str__(self):
        return self.__repr__()

def compose_linkedlist(ary):
    if not len(ary):
        return None
    
    head = ptr = ListNode(ary[0])
    for i in range(1, len(ary)):
        ptr.next = ListNode(ary[i])
        ptr = ptr.next
    return head

def show_linkedlist(x):
    while x is not None:
        print(x)
        x = x.next


In [277]:
class Solution:
    def reverseList(self, head):
        dummy = ListNode(val=None, next=head)
        
        cur = dummy
        prev, _next = None, None
        while True:
            # if tmp_next is not None:
            #     tmp_next.next = cur
            _next = cur.next
            cur.next = prev
            cur = tmp_next
            if cur is None:
                break
            
        return cur
    
Solution().reverseList(compose_linkedlist(list(range(5))))

KeyboardInterrupt: 

In [228]:
class Solution:
    def mergeTwoLists(self, l1, l2):
        root = cur = ListNode()
        def check():
            print(f"cur: [{cur}], l1: [{l1}], l2: [{l2}]")
            
        while True:
            if l1 is None or l2 is None:
                cur.next = l2 if l1 is None else l1
                # check()
                break
                
            if l1.val < l2.val:
                cur.next = l1
                l1 = l1.next
            else:
                cur.next = l2
                l2 = l2.next
                
            cur = cur.next
            # check()
        return root.next
    
l1 = compose_linkedlist([2, 3, 5, 6])
l2 = compose_linkedlist([1, 2, 3])
Solution().mergeTwoLists(l1, l2)

cur: [1 -> 2 -> 3 -> None], l1: [2 -> 3 -> 5 -> 6 -> None], l2: [2 -> 3 -> None]
cur: [2 -> 3 -> None], l1: [2 -> 3 -> 5 -> 6 -> None], l2: [3 -> None]
cur: [2 -> 3 -> 5 -> 6 -> None], l1: [3 -> 5 -> 6 -> None], l2: [3 -> None]
cur: [3 -> None], l1: [3 -> 5 -> 6 -> None], l2: [None]
cur: [3 -> 3 -> 5 -> 6 -> None], l1: [3 -> 5 -> 6 -> None], l2: [None]


1 -> 2 -> 2 -> 3 -> 3 -> 5 -> 6 -> None

## Merge k Sorted Lists (Skip for now)

In [52]:
# Definition for singly-linked list.
class ListNode(object):
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
        
    def __repr__(self):
        return f"{self.val} -> {self.next}"
    
    def __str__(self):
        return self.__repr__()
        
        
        
class Solution:
    def __init__(self):
        self.ary = []
    
    def mergeKLists(self, lists):
        """"""
        import heapq as hq
        
        root = cur = ListNode()
        for i in range(len(lists)):
            if lists[i] is not None:
                hq.heappush(self.ary, (lists[i].val, i))

        while len(self.ary) > 0:
            _, idx = hq.heappop(self.ary)
            cur.next = lists[idx]
            lists[idx] = lists[idx].next
            
            cur = cur.next

            if lists[idx] is not None:
                hq.heappush(self.ary, (lists[idx].val, idx))
            # else:
            #     print(f"linked_list {idx} done")
            
            if len(self.ary) == 1:
                cur.next = lists[hq.heappop(self.ary)[1]]
                break
                
            # print(f"[{idx}] chosen: {lists[idx].val if lists[idx] is not None else None}, cur: {cur.val}")
        return root.next
        
lists = [
    compose_linkedlist([1]),
    # compose_linkedlist([]),
    # compose_linkedlist([100, 101, 103, 104]),
]
Solution().mergeKLists(lists)

1 -> None

## Spiral Matrix

In [77]:
# class Solution:
#     def spiralOrder(self, matrix):
#         ret, sign, horizon = [], 1, True
#         m = [0, len(matrix)]
#         n = [0, len(matrix[0])]
#         cnt, i, j = 0, 0, 0
#         hit_end_cnt = 0
#         while True:
#             ret.append(matrix[i][j])
#             # print(m, n, [i, j], horizon, sign)
#             if horizon and sign > 0 and j + 1 >= n[1]:
#                 m[0] += 1
#                 horizon = not horizon
#                 hit_end_cnt += 1
#                 if hit_end_cnt > 0 and hit_end_cnt % 2 == 0: sign = -sign
#             elif horizon and sign < 0 and j - 1 < n[0]:
#                 m[1] -= 1
#                 horizon = not horizon
#                 hit_end_cnt += 1
#                 if hit_end_cnt > 0 and hit_end_cnt % 2 == 0: sign = -sign
#             elif not horizon and sign > 0 and i + 1 >= m[1]:
#                 n[1] -= 1
#                 horizon = not horizon
#                 hit_end_cnt += 1
#                 if hit_end_cnt > 0 and hit_end_cnt % 2 == 0: sign = -sign
#             elif not horizon and sign < 0 and i - 1 < m[0]:
#                 n[0] += 1
#                 horizon = not horizon
#                 hit_end_cnt += 1
#                 if hit_end_cnt > 0 and hit_end_cnt % 2 == 0: sign = -sign
                
#             # print(f"\tEnd {m}, {n}")
#             if m[0] >= m[1] or n[0] >= n[1]: 
#                 break
#             # TODO
#             if cnt >= 100: break
            
#             if horizon: j += sign
#             if not horizon: i += sign
#             cnt += 1
#         return ret

class Solution:
    def spiralOrder(self, matrix):
        ret = []
        m = [0, len(matrix)]
        n = [0, len(matrix[0])]
        cnt, i, j = 0, 0, 0
        rows, cols = matrix, list(zip(*matrix))
        print(np.array(matrix))
        while True:
            if cnt % 4 == 0: 
                s, e = n
                # print(f"0: rows {i}, {s}:{e}")
                ret.extend(rows[i][s:e])
                m[0] += 1
                j = n[1] - 1
            if cnt % 4 == 1: 
                s, e = m
                # print(f"1: cols {j}, {s}:{e}")
                ret.extend(cols[j][s:e])
                n[1] -= 1
                i = m[1] - 1
            if cnt % 4 == 2:
                s, e = n
                # print(f"2: rows {i}, {s}:{e}")
                ret.extend(rows[i][s:e][::-1])
                m[1] -= 1
                j = n[0]
            if cnt % 4 == 3:
                s, e = m
                # print(f"3: cols {j}, {s}:{e}")
                ret.extend(cols[j][s:e][::-1])
                n[0] += 1
                i = m[0]
                
            if m[0] >= m[1] or n[0] >= n[1]: break
            cnt += 1
        return ret
        
# matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # [[1,2,3],[4,5,6],[7,8,9]] 
matrix = np.arange(20).reshape([4, 5]).tolist()
Solution().spiralOrder(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[0, 1, 2, 3, 4, 9, 14, 19, 18, 17, 16, 15, 10, 5, 6, 7, 8, 13, 12, 11]

## Max sub array

Not an easy one

In [25]:
class Solution:
    def maxSubArray(self, nums):
        """"""
        dp = [nums[0]]
        _max = nums[0]
        for i, e in enumerate(nums[1:], 1):
            dp.append(e + (dp[i - 1] if dp[i - 1] > 0 else 0))
            if i == len(nums) - 1:
                print(np.stack([dp, nums]))
            _max = max(_max, dp[i])
            
        return _max
    
nums = [-2,1,-3,4,-1,2,1,-5,4]
Solution().maxSubArray(nums)

[[-2  1 -2  4  3  5  6  1  5]
 [-2  1 -3  4 -1  2  1 -5  4]]


6

## Word Search

In [5]:
%%time

def exist(board, word):
    rows, cols = len(board), len(board[0])
    directions = [(0, 1), (0, -1), (1, 0), (-1, 0)]
    visited = set()

    def dfs(r, c, i):
        if i == len(word):
            return True

        if (
            r < 0 or c < 0 or
            r >= rows or c >= cols or
            (r, c) in visited or
            board[r][c] != word[i]
        ):
            return False

        # print(f"{i}: [{r},{c}] {visited}")
        visited.add((r, c))
        for dr, dc in directions:
            if dfs(r + dr, c + dc, i + 1): return True
            
        visited.remove((r, c))
        return False


    for r in range(rows):
        for c in range(cols):
            if dfs(r, c, 0):
                return True
    return False

board = [["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"]]
word = "AAAAAAAAAAAABAA"
exist(board, word)

CPU times: user 1.14 s, sys: 6.87 ms, total: 1.14 s
Wall time: 1.15 s


False

In [6]:
%%time

class Solution:
    def __init__(self):
        """"""
        self.word = None
        self.board = None
        self.coord = set()
        self.m, self.n = None, None
        # up, right, down, left
        self.directions = [(-1, 0), (0, 1), (1, 0), (0, -1)]
    
    def exist(self, board, word):
        self.word = word
        self.board = board
        self.m, self.n = len(board), len(board[0])
        if self.m * self.n < len(word):
            return False
            
        w_idx = 0
        for i in range(self.m):
            for j in range(self.n):
                if board[i][j] == self.word[w_idx]:
                    if self.dfs(w_idx, i, j):
                        return True
                    
        return False

    def dfs(self, w_idx, i, j):
        """"""
        self.coord.add((i, j))
        # print(f"{w_idx}: {self.word[w_idx]} [{i}, {j}] {self.coord}")
        if w_idx >= len(self.word) - 1: return True
        
        for r, c in self.directions:
            ii, jj = (i + r, j + c)
            
            if (
                # rows, cols not overflow
                ii >= 0 and ii <= self.m - 1 and jj >= 0 and jj <= self.n - 1
                # not visited
                and (ii, jj) not in self.coord
                # match next charactor
                and self.board[ii][jj] == self.word[w_idx + 1]
            ):
                if self.dfs(w_idx + 1, ii, jj): 
                    return True
                    
        self.coord.remove((i, j))
        return False
    

board = [["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"]]
word = "AAAAAAAAAAAABAA"

# board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]]
# word = "ABCB"
print(np.array(board), "\n")
Solution().exist(board, word)

[['A' 'A' 'A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A' 'A' 'A']] 

CPU times: user 1.44 s, sys: 23.7 ms, total: 1.46 s
Wall time: 1.67 s


False

### Time exceeded

In [21]:
%%time

class Solution:
    def exist(self, board, word):
        w_idx = 0
        m, n = len(board), len(board[0])
        if m * n < len(word):
            return False
        
        directions = [(-1, 0), (0, 1), (1, 0), (0, -1)]
        
        for i in range(m):
            for j in range(n):
                if board[i][j] == word[w_idx]:
                    stack = [(0, i, j, set())]
                    while len(stack):
                        _w_idx, ii, jj, coord = stack.pop()
                        # print(f"{_w_idx}, {word[_w_idx]}, [{ii}, {jj}], coord: {coord}")
                        
                        if _w_idx >= len(word) - 1: return True
                        
                        next_word = word[_w_idx + 1]
                        for r, c in directions:
                            iii, jjj = ii + r, jj + c
                            if (
                                iii >= 0 and iii < m and jjj >= 0 and jjj < n
                                and (iii, jjj) not in coord 
                                and board[iii][jjj] == next_word
                            ):
                                stack.append( (_w_idx + 1, iii, jjj, coord | set([(iii, jjj)])) )

                        # if len(ary): stack.extend(ary)
        return False
    
board = [["A","A","A","A","A","A"],
         ["A","A","A","A","A","A"],
         ["A","A","A","A","A","A"],
         ["A","A","A","A","A","A"],
         ["A","A","A","A","A","A"],
         ["A","A","A","A","A","A"]]
word = "AAAAAAAAAAAABAA"

# board = [["A","B","C","E"],
#          ["S","F","C","S"],
#          ["A","D","E","E"]]
# word = "ABCB"
# print(np.array(board), "\n")
Solution().exist(board, word)

CPU times: user 1.93 s, sys: 12.1 ms, total: 1.94 s
Wall time: 2.02 s


False

## Jump Game

No need to consider all possible jump combinations, once the max of past jump beyond the point of **zero**, that means you could definitely find a way to jump across the dead index (zero)

In [ ]:
class Solution:
    def canJump(self, nums) -> bool:
        """"""
        past_maxt = None
        for i, e in enumerate(nums[:-1]):
            if e != 0:
                past_maxt = max(past_maxt, i + e) if past_maxt is not None else i + e
            else:
                # Found max of past step couldn't step across this index of value zero
                if past_maxt is None or past_maxt <= i:
                    print("Dead end")
                    return False
            print(past_maxt)
        return True
    
Solution().canJump([3,2,1,0,4])

## Combination Sum

In [24]:
class Solution:
    def combinationSum(self, candidates, target):
        candidates = sorted(candidates)
        ret = []
        
        def dfs(i, t, cache):
            """"""
            cur = candidates[i]
            # print(f"[{i}], cur: {cur}, t: {t}")
            for cnt in range(t // cur, -1, -1):
                next_t = t - cur * cnt
                next_cache = cache + [cur] * cnt
                # Hit and collect
                if next_t == 0:
                    ret.append(next_cache)
                    continue

                if next_t > 0 and i + 1 < len(candidates):
                    dfs(i + 1, next_t, next_cache)
                
        dfs(0, target, [])
        return ret

Solution().combinationSum([2, 7, 6, 3, 5, 1], 9)

[[1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 2],
 [1, 1, 1, 1, 1, 1, 3],
 [1, 1, 1, 1, 1, 2, 2],
 [1, 1, 1, 1, 2, 3],
 [1, 1, 1, 1, 5],
 [1, 1, 1, 2, 2, 2],
 [1, 1, 1, 3, 3],
 [1, 1, 1, 6],
 [1, 1, 2, 2, 3],
 [1, 1, 2, 5],
 [1, 1, 7],
 [1, 2, 2, 2, 2],
 [1, 2, 3, 3],
 [1, 2, 6],
 [1, 3, 5],
 [2, 2, 2, 3],
 [2, 2, 5],
 [2, 7],
 [3, 3, 3],
 [3, 6]]

In [25]:
class Solution:
    def combinationSum(self, l, t):
        self.t = t
        self.res = []
        for i in range(len(l)):
            self.dfs(cand=l[i:],c=[l[i]])
        return self.res
    def dfs(self, cand, c):
        if sum(c) == self.t:
            self.res.append(c)
            
        for i in range(len(cand)):
            if sum(c) + cand[i] == self.t:
                self.res.append(c + [cand[i]])
            elif sum(c) + cand[i] < self.t:
                self.dfs(cand=cand[i:],c=c+[cand[i]])

Solution().combinationSum([2, 3, 6, 7], 7)

[[2, 2, 3], [7]]

## Best Time to Buy and Sell Stock

I additional write the bounding index of max profit --> [start, end, profit], 
actually the question did not demand this information.

In [26]:
class Solution:
    def maxProfit(self, prices):
        mn_idx, profix = 0, [-1, -1, 0] # [start, end, profit]
        for i in range(1, len(prices)):
            cur = prices[i]
            if cur - prices[mn_idx] > profix[-1]:
                profix = [mn_idx, i, cur - prices[mn_idx]]
                
            if cur < prices[mn_idx]: mn_idx = i
                
        return profix[-1]
    
class Solution:
    """Solution which not keep the bounding indices, save memories."""
    def maxProfit(self, prices):
        if not len(prices): return 0
        
        mn, profix = prices[0], -1
        for i in range(1, len(prices)):
            cur = prices[i]
            profix = max(profix, cur - mn)
            mn = min(mn, cur)
                
        return profix
            
Solution().maxProfit([7,2,5,3,6,4,1,10])

9

# Misc

In [233]:
data = {"headers": {"Trips": ["id", "client_id", "driver_id", "city_id", "status", "request_at"], "Users": ["users_id", "banned", "role"]}, "rows": {"Trips": [["1", "1", "10", "1", "completed", "2013-10-01"], ["2", "2", "11", "1", "cancelled_by_driver", "2013-10-01"], ["3", "3", "12", "6", "completed", "2013-10-01"], ["4", "4", "13", "6", "cancelled_by_client", "2013-10-01"], ["5", "1", "10", "1", "completed", "2013-10-02"], ["6", "2", "11", "6", "completed", "2013-10-02"], ["7", "3", "12", "6", "completed", "2013-10-02"], ["8", "2", "12", "12", "completed", "2013-10-03"], ["9", "3", "10", "12", "completed", "2013-10-03"], ["10", "4", "13", "12", "cancelled_by_driver", "2013-10-03"]], "Users": [["1", "No", "client"], ["2", "Yes", "client"], ["3", "No", "client"], ["4", "No", "client"], ["10", "No", "driver"], ["11", "No", "driver"], ["12", "No", "driver"], ["13", "No", "driver"]]}}
data

{'headers': {'Trips': ['id',
   'client_id',
   'driver_id',
   'city_id',
   'status',
   'request_at'],
  'Users': ['users_id', 'banned', 'role']},
 'rows': {'Trips': [['1', '1', '10', '1', 'completed', '2013-10-01'],
   ['2', '2', '11', '1', 'cancelled_by_driver', '2013-10-01'],
   ['3', '3', '12', '6', 'completed', '2013-10-01'],
   ['4', '4', '13', '6', 'cancelled_by_client', '2013-10-01'],
   ['5', '1', '10', '1', 'completed', '2013-10-02'],
   ['6', '2', '11', '6', 'completed', '2013-10-02'],
   ['7', '3', '12', '6', 'completed', '2013-10-02'],
   ['8', '2', '12', '12', 'completed', '2013-10-03'],
   ['9', '3', '10', '12', 'completed', '2013-10-03'],
   ['10', '4', '13', '12', 'cancelled_by_driver', '2013-10-03']],
  'Users': [['1', 'No', 'client'],
   ['2', 'Yes', 'client'],
   ['3', 'No', 'client'],
   ['4', 'No', 'client'],
   ['10', 'No', 'driver'],
   ['11', 'No', 'driver'],
   ['12', 'No', 'driver'],
   ['13', 'No', 'driver']]}}

In [236]:
df_trips = pd.DataFrame(data["rows"]["Trips"], columns=data["headers"]["Trips"])
df_users = pd.DataFrame(data["rows"]["Users"], columns=data["headers"]["Users"])
display(df_trips.head())
display(df_users.head())

id client_id driver_id city_id               status  request_at
0  1         1        10       1            completed  2013-10-01
1  2         2        11       1  cancelled_by_driver  2013-10-01
2  3         3        12       6            completed  2013-10-01
3  4         4        13       6  cancelled_by_client  2013-10-01
4  5         1        10       1            completed  2013-10-02

users_id banned    role
0        1     No  client
1        2    Yes  client
2        3     No  client
3        4     No  client
4       10     No  driver

In [240]:
df_trips.info(), df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          10 non-null     object
 1   client_id   10 non-null     object
 2   driver_id   10 non-null     object
 3   city_id     10 non-null     object
 4   status      10 non-null     object
 5   request_at  10 non-null     object
dtypes: object(6)
memory usage: 608.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   users_id  8 non-null      object
 1   banned    8 non-null      object
 2   role      8 non-null      object
dtypes: object(3)
memory usage: 320.0+ bytes


(None, None)

In [ ]:
df_trips.join

In [244]:
tmp_users = df_users.query("banned == 'No'")

df_ret = (df_trips
             .merge(tmp_users, left_on="client_id", right_on="users_id")
             .merge(tmp_users, left_on="driver_id", right_on="users_id"))
df_ret

id client_id driver_id city_id               status  request_at users_id_x  \
0   1         1        10       1            completed  2013-10-01          1   
1   5         1        10       1            completed  2013-10-02          1   
2   9         3        10      12            completed  2013-10-03          3   
3   3         3        12       6            completed  2013-10-01          3   
4   7         3        12       6            completed  2013-10-02          3   
5   4         4        13       6  cancelled_by_client  2013-10-01          4   
6  10         4        13      12  cancelled_by_driver  2013-10-03          4   

  banned_x  role_x users_id_y banned_y  role_y  
0       No  client         10       No  driver  
1       No  client         10       No  driver  
2       No  client         10       No  driver  
3       No  client         12       No  driver  
4       No  client         12       No  driver  
5       No  client         13       No  driver  
6       No  client         13       No  driver

In [272]:
import heapq

ary = []
heapq.heapify(ary)
for i in range(3, 0, -1):
    heapq.heappush(ary, i)
ary

[1, 3, 2]

In [273]:
print(heapq.heappop(ary))
print(heapq.heappop(ary))
print(heapq.heappop(ary))

1
2
3
